tensorflow:
  ports:
  - ${PUBLIC_PORT}:8888/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  entrypoint:
  - /bin/sh
  - -c
  - jupyter notebook --port=8888 --ip=0.0.0.0
  image: davidchiu/tensorflow09:cpu-jupyter
  privileged: true
  volumes:
  - ${VOLUME_NAME}:${VOLUME_MOUNT_PATH}
  working_dir: /notebooks
  stdin_open: true
  volume_driver: ${VOLUME_DRIVER}